# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Arc.h \
    ./DataProcess.h \
    ./Dijkstra.h \
    ./Path.h \
    ./Hash.h \
    ./HashTable.h \
    ./ListGraph.h \
    ./PriorityQueue.h \
    ./Storage.h \
    ./Vertex.h \
    ./BeijingSubwayInfoSystenApplication.h
SOURCES += ./BeijingSubwayInfoSystenApplication.cpp \
    ./main.cpp
FORMS += ./BeijingSubwayInfoSystenApplication.ui \
    ./PathSearchWindow.ui
RESOURCES += BeijingSubwayInfoSystenApplication.qrc
