# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = BeijingSubwayInfoSystenApplication
DESTDIR = ./x64/Debug
CONFIG += console
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(BeijingSubwayInfoSystenApplication.pri)
